# Generated by Django 6.0.4 on 2026-05-12 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retencion', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteraCliente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vin', models.CharField(db_index=True, max_length=150)),
                ('vin_normalizado', models.CharField(db_index=True, max_length=150, unique=True)),
                ('nombre_cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('celular', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('marca_vehiculo', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.CharField(blank=True, max_length=150, null=True)),
                ('ano_modelo', models.SmallIntegerField(blank=True, null=True)),
                ('fecha_venta', models.DateField(blank=True, db_index=True, null=True)),
                ('folio_factura', models.CharField(blank=True, max_length=50, null=True)),
                ('vendedor', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_os', models.DateField(blank=True, null=True)),
                ('id_os', models.CharField(blank=True, max_length=50, null=True)),
                ('asesor_servicio', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('dias_os_a_actual', models.IntegerField(blank=True, null=True)),
                ('meses_actual_a_venta', models.IntegerField(blank=True, null=True)),
                ('franja_retencion', models.CharField(blank=True, max_length=50, null=True)),
                ('prioridad_prospeccion', models.CharField(blank=True, max_length=50, null=True)),
                ('kilometraje', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_gestion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONTACTADO', 'Contactado'), ('CITA_AGENDADA', 'Cita agendada'), ('NO_CONTACTADO', 'No contactado'), ('NO_INTERESADO', 'No interesado'), ('CERRADO', 'Cerrado')], db_index=True, default='PENDIENTE', max_length=30)),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('origen', models.CharField(default='AUTOMATICO', max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('asesor_asignado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartera_clientes_asignados', to='usuarios.usuario')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carteras_creadas', to='usuarios.usuario')),
                ('venta', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='asignaciones_cartera', to='retencion.ordenservicioventadiautos')),
            ],
            options={
                'db_table': 'cartera_clientes',
                'ordering': ['-asignado_en', '-id'],
                'managed': True,
                'indexes': [models.Index(fields=['asesor_asignado', 'estado_gestion'], name='cartera_cli_asesor__c36b91_idx'), models.Index(fields=['fecha_venta'], name='cartera_cli_fecha_v_e81d8c_idx'), models.Index(fields=['ano_modelo', 'modelo'], name='cartera_cli_ano_mod_6c53f7_idx'), models.Index(fields=['meses_actual_a_venta'], name='cartera_cli_meses_a_344aad_idx'), models.Index(fields=['-asignado_en'], name='cartera_cli_asignad_357649_idx')],
            },
        ),
    ]
