# Generated by Django 5.2.5 on 2026-06-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0001_initial'),
        ('retencion', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='carteracliente',
            index=models.Index(fields=['activo', 'vin_normalizado'], name='idx_cartera_activo_vin'),
        ),
    ]
