# Generated by Django 5.2.5 on 2026-06-16 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0002_carteracliente_idx_cartera_activo_vin'),
        ('retencion', '0002_alter_detalleventaspostventalimpia_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='carteracliente',
            name='cartera_cli_asignad_357649_idx',
        ),
        migrations.AddField(
            model_name='carteracliente',
            name='detalle_gestion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='carteracliente',
            name='estado_gestion',
            field=models.CharField(blank=True, db_index=True, default='PENDIENTE', max_length=255),
        ),
        migrations.AddIndex(
            model_name='carteracliente',
            index=models.Index(fields=['asignado_en'], name='cartera_cli_asignad_b92443_idx'),
        ),
    ]
