# Generated by Django 6.0.4 on 2026-05-12 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(blank=True, max_length=70, null=True)),
                ('usuario', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=255)),
                ('contrasena', models.CharField(max_length=255)),
                ('agencia', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('rol', models.ForeignKey(db_column='rol', on_delete=django.db.models.deletion.PROTECT, to='usuarios.rol')),
            ],
            options={
                'db_table': 'usuarios',
                'managed': True,
            },
        ),
    ]
