# Generated by Django 6.0.4 on 2026-06-03 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(blank=True, default='', max_length=120)),
                ('auto_interes', models.CharField(blank=True, default='', max_length=255)),
                ('fecha_hora_cita', models.DateTimeField(blank=True, null=True)),
                ('asistencia', models.BooleanField(default=False)),
                ('tipo_cita', models.CharField(blank=True, default='', max_length=120)),
                ('fuente_prospeccion', models.CharField(blank=True, default='', max_length=120)),
                ('asesor_digital', models.CharField(blank=True, default='', max_length=200)),
                ('asesor_piso', models.CharField(blank=True, default='', max_length=200)),
                ('comentarios', models.CharField(blank=True, default='', max_length=2000)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='clientes.clientecomercial')),
            ],
            options={
                'db_table': 'citas',
                'managed': True,
            },
        ),
    ]
