# Generated by Django 6.0.4 on 2026-05-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteComercial',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, default='', max_length=200)),
                ('telefono', models.CharField(db_index=True, max_length=32, unique=True)),
                ('correo', models.EmailField(blank=True, default='', max_length=254)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clientes_comerciales',
                'managed': True,
            },
        ),
    ]
