# Generated by Django 5.2.5 on 2026-06-15 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retencion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleventaspostventalimpia',
            options={'managed': False, 'ordering': ['-ore_fechaord']},
        ),
    ]
