# Generated by Django 6.0.4 on 2026-05-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaServicio',
            fields=[
                ('id_encuesta', models.AutoField(primary_key=True, serialize=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('numero_OS', models.CharField(blank=True, default='', max_length=200)),
                ('satisfaccion_agendar_cita', models.CharField(blank=True, default='', max_length=200)),
                ('satisfaccion_exp_area_servicio', models.CharField(blank=True, default='', max_length=200)),
                ('mostraron_inventario_inicial_vehiculo', models.BooleanField(default=False)),
                ('explicacion_clara_trabajo_realizado', models.BooleanField(default=False)),
                ('invitacion_realizar_inventario', models.BooleanField(default=False)),
                ('entrego_reporte_multipuntos', models.BooleanField(default=False)),
                ('trabajo_realizado_cumple_espectativa', models.BooleanField(default=False)),
                ('comentario', models.CharField(blank=True, default='', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'encuestas_servicio',
                'managed': True,
            },
        ),
    ]
