# Generated by Django 6.0.4 on 2026-05-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuestaservicio',
            name='satisfaccion_agendar_cita',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='encuestaservicio',
            name='satisfaccion_exp_area_servicio',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
