# Generated by Django 6.0.4 on 2026-06-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_alter_encuestaservicio_satisfaccion_agendar_cita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuestaservicio',
            name='asesor',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
