# Generated by Django 6.0.4 on 2026-05-18 12:36

import avaluos.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaluoUsado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('fecha_avaluo', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_toma_cuenta', models.DateTimeField(blank=True, null=True)),
                ('agenda_valuacion', models.DateTimeField(blank=True, null=True)),
                ('asesor_ventas', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('vendedor', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('tipo_valuacion', models.CharField(blank=True, choices=[('valuacion', 'Valuación'), ('fresh_up', 'Fresh Up'), ('valuacion_servicio', 'Valuación de servicio'), ('valuacion_bdc', 'Valuación de BDC')], default='valuacion', max_length=40, null=True)),
                ('tipo_toma', models.CharField(blank=True, choices=[('de_servicio', 'De servicio'), ('canal', 'Canal')], default='', max_length=40, null=True)),
                ('marca_auto', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('modelo', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('anio_modelo', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('version', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('serie', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('placas', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('kilometraje', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('color', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('precio_guia', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('precio_compra_libro_azul', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('precio_venta_libro_azul', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('costo_reparacion', models.CharField(blank=True, default='0.00', max_length=120, null=True)),
                ('costo_estimado', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('costo_mecanica_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('oferta_inicial', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('oferta_final', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('origen_valuacion', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('descripcion', models.TextField(blank=True, default='', max_length=4000, null=True)),
                ('observaciones', models.TextField(blank=True, default='', max_length=4000, null=True)),
                ('comentarios', models.TextField(blank=True, default='Valuación', max_length=4000, null=True)),
                ('ganador_subasta', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('etapa_proceso', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('checklist_100', models.JSONField(blank=True, default=dict)),
                ('tecnico_finalizado', models.BooleanField(default=False)),
                ('fecha_tecnico_finalizado', models.DateTimeField(blank=True, null=True)),
                ('valuacion_terminada', models.BooleanField(default=False)),
                ('fecha_valuacion_terminada', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='avaluos_usados', to='clientes.clientecomercial')),
            ],
            options={
                'db_table': 'avaluos',
                'ordering': ['-creado'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AvaluoUsadoEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=avaluos.models.avaluo_evidencia_upload_to)),
                ('nombre', models.CharField(blank=True, default='', max_length=255)),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video'), ('archivo', 'Archivo')], default='archivo', max_length=20)),
                ('categoria_concepto', models.CharField(choices=[('estetico', 'Estético'), ('mecanico', 'Mecánico'), ('hyp', 'HYP')], default='estetico', max_length=20)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descripcion', models.CharField(blank=True, default='', max_length=500)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('avaluo', models.ForeignKey(db_column='id_avaluo', on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='avaluos.avaluousado')),
            ],
            options={
                'db_table': 'avaluos_evidencias',
                'ordering': ['-creado'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConceptoAvaluo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, default='', max_length=4000)),
                ('tipo_concepto', models.CharField(choices=[('mecanico', 'Mecánico'), ('estetico', 'Estético'), ('hyp', 'HYP')], default='mecanico', max_length=20)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('avaluo', models.ForeignKey(db_column='id_avaluo', on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='avaluos.avaluousado')),
            ],
            options={
                'db_table': 'conceptos_avaluos',
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
