# Generated by Django 6.0.4 on 2026-05-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaluos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaluousado',
            name='comentarios_checklist',
            field=models.TextField(blank=True, default='', max_length=4000, null=True),
        ),
    ]
